name: sudety-raport-ci-cd

on:
  push:
    branches: [masterm, main]

jobs:
  build:
    defaults:
      run:
        working-directory: sudety-raport-frontend
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: sr-report
          path: sr-report/
          retention-days: 30
